<a href="https://colab.research.google.com/github/o-semenkova/ml_home_tasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [26]:
import random
import numpy as np

In [27]:
def get_array_with_one_random_element():
  element = random.uniform(0, 1)
  return [element]

def create_n_size_vector(n):
  random_list = [get_array_with_one_random_element() for _ in range(n)]
  return np.array(random_list)

v = create_n_size_vector(10)
print(v, v.shape)

[[0.46998077]
 [0.31774001]
 [0.34239487]
 [0.06142044]
 [0.11547193]
 [0.77676424]
 [0.62541758]
 [0.98509749]
 [0.6133933 ]
 [0.46089127]] (10, 1)


In [28]:
v2 = np.random.rand(10)
print(v2, v2.shape)

[0.63164982 0.92121356 0.11791247 0.17363523 0.81624278 0.20749192
 0.15917276 0.1169961  0.54390061 0.50268544] (10,)


In [29]:
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
            [29, 32, 35]])
print(matrix, matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]] (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [30]:
number_to_add = 10
rounded_vector = np.round(v + number_to_add, decimals=2)
print(rounded_vector)

[[10.47]
 [10.32]
 [10.34]
 [10.06]
 [10.12]
 [10.78]
 [10.63]
 [10.99]
 [10.61]
 [10.46]]


In [31]:
number = 2

result = np.multiply(matrix, number)
print(result)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [32]:
squared = np.square(v2)
print(squared)

[0.39898149 0.84863441 0.01390335 0.03014919 0.66625227 0.0430529
 0.02533597 0.01368809 0.29582787 0.25269265]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [33]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [34]:
# Перевiримо умови множення (1 матриця стовпцi = 2 матриця рядки)

A.shape, B.shape

((3, 2), (2, 3))

In [35]:
result_matrix = np.dot(B,A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [36]:
# (2,2) * (2,1) = (2, 1)

print(np.dot(result_matrix, C))

[[0.5202]
 [0.2846]]


In [37]:
# (2,2) * (2,2) = (2, 2)

print(np.dot(result_matrix, D))

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [38]:
transposed_result = result_matrix.T

print(transposed_result)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [39]:
print(v.shape)
print(v.T.shape)

# Так, змiна очевидна

(10, 1)
(1, 10)


In [40]:
print(v)
print("*******************")

column_vector = np.expand_dims(v, axis=1)

print(column_vector)

# Кожен з елементiв vector був помiщений до ще одного масиву, тобто додана ще одна розмiрнiсть, що i можемо побачити з перевiрки форми

print(column_vector.shape)

[[0.46998077]
 [0.31774001]
 [0.34239487]
 [0.06142044]
 [0.11547193]
 [0.77676424]
 [0.62541758]
 [0.98509749]
 [0.6133933 ]
 [0.46089127]]
*******************
[[[0.46998077]]

 [[0.31774001]]

 [[0.34239487]]

 [[0.06142044]]

 [[0.11547193]]

 [[0.77676424]]

 [[0.62541758]]

 [[0.98509749]]

 [[0.6133933 ]]

 [[0.46089127]]]
(10, 1, 1)


In [41]:
transposed_column_vector = column_vector.T
print(transposed_column_vector)
print(transposed_column_vector.shape)

[[[0.46998077 0.31774001 0.34239487 0.06142044 0.11547193 0.77676424
   0.62541758 0.98509749 0.6133933  0.46089127]]]
(1, 1, 10)
