<a href="https://colab.research.google.com/github/o-semenkova/ml_home_tasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [4]:
import random
import numpy as np

In [9]:
def get_array_with_one_random_element():
  element = random.uniform(0, 1)
  return [element]

def create_n_size_vector(n):
  random_list = [get_array_with_one_random_element() for _ in range(n)]
  return np.array(random_list)

v = create_n_size_vector(10)
print(v, v.shape)

[[0.72411547]
 [0.48816988]
 [0.08528869]
 [0.73786542]
 [0.00940466]
 [0.68863583]
 [0.0712413 ]
 [0.80970287]
 [0.17782856]
 [0.16169844]] (10, 1)


In [10]:
v2 = np.random.rand(10)
print(v2, v2.shape)

[0.39974395 0.25136548 0.9947744  0.33026073 0.15690327 0.71480483
 0.39836357 0.91375861 0.34233459 0.23292072] (10,)


In [11]:
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
            [29, 32, 35]])
print(matrix, matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]] (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [12]:
number_to_add = 10
rounded_vector = np.round(v + number_to_add, decimals=2)
print(rounded_vector)

[[10.72]
 [10.49]
 [10.09]
 [10.74]
 [10.01]
 [10.69]
 [10.07]
 [10.81]
 [10.18]
 [10.16]]


In [13]:
number = 2

result = np.multiply(matrix, number)
print(result)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [14]:
squared = np.square(v2)
print(squared)

[0.15979523 0.0631846  0.98957611 0.10907215 0.02461864 0.51094595
 0.15869353 0.8349548  0.11719297 0.05425206]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.


